coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: auto
        threshold: 20%
        # advanced settings
        branches:
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
  ignore:
    - "3rd/**/*"
    - "/usr/include"
    - "apps/**/*"
    - "tests/**/*"
    - "build-debug"
    - "build-release"