name: clang-format Check
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'modules'
          - 'apps'
          - 'tests'
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++ programs.
      uses: jidicula/clang-format-action@v4.6.2
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path }}
