# This is a basic workflow to help you get started with Actions

name: ubuntu22.04.clang

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    name: "ubuntu 22.04 Clang"
    env:
      CC: clang
      CXX: clang++
      LD_LIBRARY_PATH: ${{github.workspace}}/3rd/lib
      CLANG_FORMAT: OFF
      CLANG_TIDY: OFF
      PARDISO: OFF
      DOCS: OFF

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install additional deps
        working-directory: ${{github.workspace}}
        run: |
          sudo apt-get update
          ${{github.workspace}}/deps/prepare.sh
          ${{github.workspace}}/deps/change-3rd-url.py

      - name: Cache Third
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/3rd
          key: ubt2204-clang-3rd-${{ hashFiles('**/change-3rd-url.py', '**/deps.cmake') }}

      - name: Configure git
        env:
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Debug Mode
        working-directory: ${{github.workspace}}
        run: make debug

      - name: Release Mode
        working-directory: ${{github.workspace}}
        run: make release

      - name: Unit Test
        working-directory: ${{github.workspace}}
        run: make test
